version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: terraform
    directories:
      - /github/chikachow
      - /github/cysp
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      shared-providers:
        group-by: dependency-name
