version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /github/chikachow
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /github/cysp
    schedule:
      interval: weekly
