name: tflint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tflint:
    name: ${{ matrix.root }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        root:
          - github/chikachow
          - github/cysp

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0

      - run: tflint --chdir="${{ matrix.root }}" --format=compact

  required:
    name: tflint
    runs-on: ubuntu-latest
    needs: tflint
    if: ${{ always() }}

    steps:
      - run: |
          if [ "${{ needs.tflint.result }}" != "success" ]; then
            exit 1
          fi
